image: node:latest

stages:
  - build
  - production

test:
  stage: test
  script:
    - npm build
  artifacts:
    paths:
      - dist/

test_ci_push:
  tags:
    - linux
    - shell
    - light
  stage: profiling
  allow_failure: false
  only:
    - new-benchmark-stage
  script:
    - git remote add github https://github.com/mcourant/gta-ynov-webmobile.git
    - touch test.dat
    - echo "This is a test" > test.dat
    - git config --global user.name "mcourant"
    - git config --global user.email "maxime.courant@ynov.com"
    - git add --all
    - git commit -m "GitLab Runner Push"
    - git push -u github master
    - cd ..

production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=gta-ynov-webmobile --api-key=b90d07c0-46b1-462c-95df-d74235d6b619
  only:
    - tags
