image: node:latest

stages:
  - install
  - build
  - push_github
  - production

install:
  stage: install
  script:
    - npm i
  artifacts:
    paths:
      - node_modules/


build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

test_ci_push:
  stage: push_github
  allow_failure: false
  script:
    - git remote add github https://mcourant:${PASSWORD_GITHUB}@github.com/mcourant/gta-ynov-webmobile.git
    - git add --all
    - git commit -m "GitLab Runner Push"
    - git push -u github master
    - cd ..

production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=gta-ynov-webmobile --api-key=b90d07c0-46b1-462c-95df-d74235d6b619 